// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using PhotoPipeline.Database;

#nullable disable

namespace PhotoPipeline.Database.MsSql.Migrations
{
    [DbContext(typeof(PhotoDbContext))]
    [Migration("20210925200036_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rtm.21474.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PhotoPipeline.Database.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("IntakeTake")
                        .HasColumnType("datetimeoffset");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Taken")
                        .HasColumnType("datetime2");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("PhotoPipeline.Database.Entities.PhotoHash", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HashValue")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PhotoId", "HashType");

                    b.HasIndex("HashType", "HashValue");

                    b.ToTable("PhotoHashes");
                });

            modelBuilder.Entity("PhotoPipeline.Database.Entities.PhotoMetadata", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PhotoId", "Key");

                    b.HasIndex("Key", "Value");

                    b.ToTable("PhotoMetadata");
                });

            modelBuilder.Entity("PhotoPipeline.Database.Entities.PhotoHash", b =>
                {
                    b.HasOne("PhotoPipeline.Database.Entities.Photo", "Photo")
                        .WithMany("Hashes")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("PhotoPipeline.Database.Entities.PhotoMetadata", b =>
                {
                    b.HasOne("PhotoPipeline.Database.Entities.Photo", "Photo")
                        .WithMany("Metadata")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("PhotoPipeline.Database.Entities.Photo", b =>
                {
                    b.Navigation("Hashes");

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
